name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-node-ios:
    runs-on: macos-14
    env:
      TARGET_ARCH: arm64
      XCODE_VERSION: 15.2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up sccache (Optional, for faster builds)
        uses: mozilla-actions/sccache-action@v0.0.6
        env:
          SCCACHE_GHA_ENABLED: 'true'

      - name: Select Xcode Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: ${{ env.XCODE_VERSION }}

      - name: Build iOS Node Binary
        run: |
          # Workaround: Python 3.12 removed distutils, but Node.js build may still expect setuptools
          python3.12 -m venv ./venv
          source venv/bin/activate
          pip install setuptools

          # Run your simplified build script
          ./tools/ios_bin_prepare.sh

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-ios-arm64-binary
          path: out/Release/iphone-bin/node-arm64
          if-no-files-found: error

      - name: Debug - List Files (Optional)
        if: always()
        run: |
          find out/Release -type f